---
Organizations:
  - &OrdererOrg
    Name: OrdererOrg
    ID: OrdererMSP
    MSPDir: crypto-config/ordererOrganizations/example.com/msp

  - &Org1
    Name: Org1MSP
    ID: Org1MSP
    MSPDir: crypto-config/peerOrganizations/org1.example.com/msp

  - &Org2
    Name: Org2MSP
    ID: Org2MSP
    MSPDir: crypto-config/peerOrganizations/org2.example.com/msp

  - &Org3
    Name: Org3MSP
    ID: Org3MSP
    MSPDir: crypto-config/peerOrganizations/org3.example.com/msp

Capabilities:
  Channel: &ChannelCapabilities
    V2_0: true

  Orderer: &OrdererCapabilities
    V2_0: true

  Application: &ApplicationCapabilities
    V2_0: true

Application: &ApplicationDefaults
  Policies:
    Readers:
      Type: Signature
      Rule: "OR('Org1MSP.peer', 'Org2MSP.peer', 'Org3MSP.peer')"
    Writers:
      Type: Signature
      Rule: "OR('Org1MSP.peer', 'Org2MSP.peer')"
    Admins:
      Type: Signature
      Rule: "OR('Org1MSP.admin', 'Org2MSP.admin')"

Orderer: &OrdererDefaults
  OrdererType: solo
  Addresses:
    - orderer.example.com:7050

  Capabilities:
    <<: *OrdererCapabilities

  Organizations:
    - *OrdererOrg

Channel: &ChannelDefaults
  Capabilities:
    <<: *ChannelCapabilities

Profiles:
  ThreeOrgsChannel:
    Consortium: SampleConsortium
    Application:
      <<: *ApplicationDefaults
      Organizations:
        - *Org1
        - *Org2
        - *Org3
